### ISSUE TITLE
Scala 2.12.0-M4 dependency

### ISSUE THREAD

**Issue by keithschulze** [scijava/scripting-scala#2]
Just a question as to why scripting-scala depends on the pre-release 2.12.0-M4 version of Scala? Looking at the repo, it seems it was introduced for JSR-223 script engine capatibility; however, as far as I can tell this is available in Scala 2.11 too. Thanks in advance.

**Comment by ctrueden** [comment]
This issue will be moot after the merge of your PR #3, but just to answer your question: I mostly chose 2.12.0-M4 because it was the latest release version. I cannot recall if there was some more concrete reason why 2.11 did not work. In any case, will be nice to upgrade to 2.12.0 final release!
