### ISSUE TITLE
eval should sometimes make an entry in the ENGINE_SCOPE bindings

### ISSUE THREAD

**Issue by mslinn** [scijava/scripting-scala#5]
`scripting-scala`'s `eval` function does not quite match the JSR233 implementations for Nashorn and Jython. Specifically, eval should make an entry in the `ScriptContext.ENGINE_SCOPE` bindings whenever it receives a string that causes a new variable or method to be defined.

For example, this should cause a new variable called `twelve` to be defined:

    eval("val twelve = 12")

I exercise several JSR233 implementations in a test suite here, and highlight this issue [here](https://github.com/mslinn/cli-loop/blob/master/src/test/scala/com/micronautics/cli/TestyMcTestFace.scala#L237-L242).

The `scripting-java` and `scripting-clojure` projects probably suffer from the same bug.

**Comment by jpsacha** [comment]
Implementations moved recently to Scala 3 and its implementation of the Script Engine. That implementation currently has no support for bindings (https://github.com/lampepfl/dotty/issues/17237). However, the bindings are emulated in the new `ScalaAdaptedScriptEngine`.

I added a test to verify the the issue reported [here](https://github.com/mslinn/cli-loop/blob/524b79e52859f4c5ae8c850688eaaf68e0936e85/src/test/scala/com/micronautics/cli/TestyMcTestFace.scala#LL242C2-L260C43) was addressed: https://github.com/scijava/scripting-scala/blob/33f3b1b19cb88711a0db2cf2cf5a2ed26726aec3/src/test/java/org/scijava/plugins/scripting/scala/ScalaTest.java#L274
